---
# Gitlab-CI configure
variables:
  DEPLOY_HOST: 118.69.18.127
  DEPLOY_PORT: 22
  PROJECT_LOCATION: /var/www/html/home.fpt.work

stages:
  - pullgit
  
pullgit:
  stage: pullgit
  script:
    - bash ci-cd/ssh.sh "$DEPLOY_HOST" "$DEPLOY_PORT" "$PROJECT_LOCATION"
  tags:
    - dev
